import { type NextPage } from 'next'
import Head from 'next/head'
import Tweet from '@/modules/Tweet'

const TweetPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Tweet />
    </>
  )
}

export default TweetPage
