import { type NextPage } from 'next'
import Head from 'next/head'
import LikedTweets from '@/modules/LikedTweets'

const LikedTweetsPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <LikedTweets />
    </>
  )
}

export default LikedTweetsPage
