import { type NextPage } from 'next'
import Head from 'next/head'
import Profile from '@/modules/Profile'

const ProfilePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Profile />
    </>
  )
}

export default ProfilePage
