import { type NextPage } from 'next'
import Head from 'next/head'
import Layout from '@/components/Layout'
import ProfilePage from '@/modules/Profile/ProfilePage'

const Profile: NextPage = () => {
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <ProfilePage />
      </Layout>
    </>
  )
}

export default Profile
